import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { auth, clerkClient } from "@clerk/nextjs/server";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Space X Forum Demo",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();
  const username =
    userId && (await (await clerkClient()).users.getUser(userId)).username;
  return (
    <html lang="es" className="dark">
      <ClerkProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        >
          <header className="fixed top-0 w-full grid grid-cols-5 items-center gap-2 px-14 py-2 backdrop-blur-md z-50">
            <aside className="col-span-1 flex items-center justify-start gap-4">
              <a href="/">
                <h1 className="font-mono text-2xl hover:text-lime-400">
                  Space X Forum Demo
                </h1>
              </a>
            </aside>
            <nav className="col-span-3">
              <ul className="w-full flex items-center justify-center gap-4">
                <li>
                  <a
                    href="/about"
                    className="text-center inline-block px-4 py-1 text-foreground/80 hover:text-lime-400 bg-foreground/10 hover:bg-lime-400/10 rounded-full transition-all"
                  >
                    About
                  </a>
                </li>
                <li>
                  <a
                    href="/launches"
                    className="text-center inline-block px-4 py-1 text-foreground/80 hover:text-lime-400 bg-foreground/10 hover:bg-lime-400/10 rounded-full transition-all"
                  >
                    Launches
                  </a>
                </li>
              </ul>
            </nav>
            <aside className="col-span-1 flex items-center justify-end gap-4">
              <SignedIn>
                <span className="font-mono text-sm text-foreground/80">
                  {username}
                </span>
                <UserButton />
              </SignedIn>
              <SignedOut>
                <SignInButton mode="modal">
                  <Button variant="ghost" className="px-4 py-1 border-2">
                    Sign in
                  </Button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <Button className="px-4 py-1">Sign up</Button>
                </SignUpButton>
              </SignedOut>
            </aside>
          </header>
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
